In [39]:
import numpy as np

In [40]:
lista=[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [41]:
arr = np.array(lista)

In [42]:
type(arr)

numpy.ndarray

In [43]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
matriz[0][2] + matriz[1][1]

8

In [45]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [47]:
matriz[1:]

[[4, 5, 6], [7, 8, 9]]

In [48]:
matriz[1:, 0:2]

TypeError: list indices must be integers or slices, not tuple