In [1]:
import numpy as np

In [5]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
chunk_arr = arr[0:6]
chunk_arr

array([0, 1, 2, 3, 4, 5])

In [8]:
chunk_arr[:]=0
chunk_arr

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [10]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [13]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
arr_copy[:]=1
arr_copy

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])