In [22]:
import numpy as np

In [23]:
scalar = np.array(42)
scalar

array(42)

In [24]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [25]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [26]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

## Agregar o eliminar dimensiones:

In [27]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [28]:
expandido = np.expand_dims(np.array([1,2,3]), axis=0)
print(expandido)
expandido.ndim


[[1 2 3]]


2

### Eliminar dimension

In [29]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3]


In [32]:
ejercicio = np.array([1,2,3], ndmin=10)
ejercicio

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [33]:
añadido = np.expand_dims(ejercicio, axis=0)
print(añadido.ndim)

11


In [36]:
reducido = np.squeeze(añadido)
print(reducido, reducido.ndim)

[1 2 3] 1
