In [2]:
import numpy as np

In [4]:
scalar = np.array(42)
scalar

array(42)

In [7]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [8]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

## Agregar o eliminar dimensiones:

In [10]:
vector = np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [14]:
expandido = np.expand_dims(np.array([1,2,3]), axis=0)
print(expandido)
expandido.ndim


[[1 2 3]]


2

### Eliminar dimension

In [17]:
print(vector, vector.ndim)
vector_2=np.squeeze(vector)
print(vector_2)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
