In [9]:
import numpy as np

In [10]:
arr = np.random.randint(1,20,10)

In [11]:
matriz = arr.reshape(2,5)

In [12]:
matriz

array([[12,  2,  3, 15, 17],
       [ 5, 13,  2, 10, 19]])

In [13]:
arr.max()

19

In [14]:
matriz.max(0)

array([12, 13,  3, 15, 19])

In [15]:
arr.argmax()

9

In [16]:
arr.min()

2

In [18]:
matriz.min(1)

array([2, 2])

In [19]:
arr.argmin()

1

In [20]:
matriz.ptp(0)

array([ 7, 11,  1,  5,  2])

In [21]:
matriz.ptp()

17

In [23]:
np.percentile(arr,50)

11.0