In [5]:
import numpy as np

In [6]:
lista = [1,2]

In [7]:
lista * 2

[1, 2, 1, 2]

In [8]:
arr = np.arange(0,10)
arr2=arr.copy()


In [10]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [11]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
matriz / matriz2

/tmp/ipykernel_1440/2494271429.py:1: RuntimeWarning: invalid value encountered in true_divide
  matriz / matriz2


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [18]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])