In [2]:
import numpy as np

In [3]:
lista = [1,2,3,4,5,6,7,8,9]
print(lista)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
arr= np.array(lista)
type(arr)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr[1] + arr[4]

7

In [7]:
matriz[1,1]

5

In [8]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [9]:
arr[::3]

array([1, 4, 7])