In [42]:
import numpy as np
from numpy import pi

In [43]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [44]:
arr.astype(np.float64)

array([1., 2., 3., 4.])

In [45]:
arr = np.array([1,2,3,4],dtype='float64')
arr.dtype

dtype('float64')

In [46]:
arr = np.array([0,1,2,3,4],dtype='float64')
arr = arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [47]:
arr = np.array([0,1,2,3,4],dtype='float64')
arr = arr.astype(np.string_)
arr

array([b'0.0', b'1.0', b'2.0', b'3.0', b'4.0'], dtype='|S32')

In [48]:
c = np.array([[1,2],[3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [49]:
cero = np.zeros((4, 4))
cero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
cero.ndim

2

In [54]:
x = np.linspace(0, 2 * pi, 100)        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [60]:
c = np.arange(36).reshape(3, 4, 3)  # 3d array
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [64]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

D=A*B
C = A @ B
print(C)
print(D)

[[5 4]
 [3 4]]
[[2 0]
 [0 4]]


In [71]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b=rg.random((2,3))
a+=3
b+=a
b